trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: CadQuery/conda-packages
      endpoint: CadQuery

jobs:
- template: conda-build.yml@templates
  parameters:
    name: Linux
    vmImage: 'ubuntu-18.04'
    py_maj: 3
    py_min: 8
    conda_bld: '3.20.3'

- template: conda-build.yml@templates
  parameters:
    name: macOS
    vmImage: 'macOS-10.15'
    py_maj: 3
    py_min: 8
    conda_bld: '3.20.3'

- template: conda-build.yml@templates
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 8
    conda_bld: '3.20.3'

- template: conda-build.yml@templates
  parameters:
    name: Linux
    vmImage: 'ubuntu-18.04'
    py_maj: 3
    py_min: 9
    conda_bld: '3.21.4'

- template: conda-build.yml@templates
  parameters:
    name: macOS
    vmImage: 'macOS-10.15'
    py_maj: 3
    py_min: 9
    conda_bld: '3.21.4'

- template: conda-build.yml@templates
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 9
    conda_bld: '3.21.4'
    
- job: Work
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  # This malformed command causes the job to fail
  # Only run this command if the succeed variable is set to false
  - script: git clone malformed input
    condition: eq(${{ parameters.succeed }}, false)
